### ISSUE TITLE
All downloaded files are only 32KB

### ISSUE THREAD

**Issue by icefirex** [irgangla/JiraAttachmentDownload#1]
![image](https://user-images.githubusercontent.com/1530893/58247160-da030f00-7d50-11e9-9c25-6e414960d14c.png)

**Comment by irgangla** [comment]
Hi, can you please check the Files with a Text-Editor or upload one of them? Most probably this is some error HTML page which is saved with the expected file name when the download fails.

**Comment by icefirex** [comment]
See attached file, it is indeed HTML
[common-client-6.2.1.1.txt](https://github.com/irgangla/JiraAttachmentDownload/files/3216327/common-client-6.2.1.1.txt)

**Comment by irgangla** [comment]
According to the error html page there is a login issue: "You must log in to access this page."
The extension expect the links to work without further authentication.
